train_transforms:
  - type: "ColorJitter"
    brightness: 1.0
    contrast: 0.5
    saturation: 1
    hue: 0.1
  - type: "RandomEqualize"
    p: 0.4
  - type: "AugMix"
  - type: "RandomHorizontalFlip"
    p: 0.3
  - type: "RandomVerticalFlip"
    p: 0.3
  - type: "GaussianBlur"
    kernel_size: [3, 3]
  - type: "RandomRotation"
    degrees: 30
  - type: "Resize"
    size: [50, 50]
  - type: "ToTensor"

val_transforms:
  - type: "Resize"
    size: [50, 50]
  - type: "ToTensor"

infer_transforms:
  - type: "Resize"
    size: [50, 50]
  - type: "ToTensor"